language: python
python:
    - "2.7"
    # 3.7 doesn't run flake8 or other things cleanly at the moment.
    - "3.6"
sudo: required
services:
    - docker
# Use cache with pip to save time.
cache: pip
before_install:
    - docker pull rehlers/overwatch
install: "pip install --upgrade -e .[tests,dev]"
before_script:
    # Run the tests inside of the docker image, but since we've mounted the directory, the results are avaialble outside of the image.
    - docker run -v ${PWD}:/opt/overwatch rehlers/overwatch /bin/bash -c "pip install --upgrade -e .[tests,dev]; cd tests; pytest -l --cov=overwatch --cov-report html --cov-branch . --durations=5"
script:
    - flake8 overwatch
after_success:
    - coveralls
