# Contains parameters shared between multiple modules
# Note that this configuration file will be imported after the shared parameters config.
# For more, see overwatch.base.config
#
# author: Raymond Ehlers <raymond.ehlers@cern.ch>, Yale University
# date: 16 July 2018

# Set debug
debug: false

# List of subsystems.
# Each subsystem listed here will have an individual page for their respective histograms.
# The HLT _MUST_ be included here!
subsystemList: &subsystemList
    - "EMC"
    - "TPC"
    - "HLT"

# Each of these subsystems will also get an individual page for access to their respective ROOT files.
subsystemsWithRootFilesToShow: *subsystemList

# Select whether to enable trending
trending: true

# Folders
# The name of the static folder on the disk.
staticFolder: &staticFolder "static"

# The name of the data folder on the disk.
dataFolder: &dataFolder "data"

# The name of the templates folder on the disk.
templateFolder: &templateFolder "templates"

# The path to the database.
databaseLocation: !joinPaths
    - "file://"
    - *dataFolder
    - "overwatch.fs"

# Location of the receiver files.
receiverData: *dataFolder
# Temporary storage location for the receiver data files.
receiverDataTempStorage: !joinPaths
    - *dataFolder
    - "tempStorage"
dataTransferLocations:
    # Overwatch sites, where the data will be transferred via rsync.
    # The values must be valid rsync paths (ie. "a@b:/path/to/dir")
    site1 : ""
    # EOS. If "EOS" is in the name, we will transfer the files via EOS.
    EOS :  "/eos/experiment/alice/overwatch/"
# Number of times we should try to transfer data when the transfer fails.
dataTransferRetries: 2

# The file extension to use when printing ROOT files.
fileExtension: "png"

# Set the logging level.
loggingLevel: "INFO"

